version: '3.4'

networks:
  backend:

services:
  engagementsapi:
    container_name: engagements-api
    image: ${DOCKER_REGISTRY-}engagementsapi
    ports: 
      - "18001:80"
    build:
      context: .
      dockerfile: EngagementsAPI/Dockerfile
    environment:
      - DB_HOST=engagementsdb
      - DB_NAME=engagements
      - DB_SA_PASSWORD=password1!
    networks:
      - backend

  engagementsdb:
    container_name: engagements-db
    image: mysql:8.0.29-oracle
    environment:
      - MYSQL_ROOT_PASSWORD=password1!
    ports:
      - '8006:3306'
    restart: always
    networks:
      - backend